version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/PrimeBank
    # dans les command on utilise collectstatic pour avoir les fichiers static dans le container (surtout pour la prod
    command: >
      sh -c "
      uv sync --frozen || uv sync &&
      uv run python manage.py migrate &&
      uv run python manage.py runserver 0.0.0.0:8000
      "
    env_file: ./.env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-config.settings}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
    volumes:
      - ./backend:/app
      - venv:/app/.venv 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  venv: 