services:
  traefik:
    image: traefik:v3.6.4
    environment:
      HOSTINGER_API_TOKEN: ${HOSTINGER_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.swarm.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik-certs:/var/traefik/certs:rw
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  error-pages:
    image: nginx:alpine
    volumes:
      - ./traefik/error-pages:/usr/share/nginx/html
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  backend:
    image: ghcr.io/epitech-msc-1/time-manager-backend:${TAG:-latest}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-PrimeBank.settings}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      DJANGO_PORT: ${DJANGO_PORT:-8000}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      VITE_PORT: ${VITE_PORT:-5173}
      PYTHONUNBUFFERED: 1
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error -H 'Accept: application/json' http://127.0.0.1:${DJANGO_PORT:-8000}/ht/",
        ]
      interval: 5s
      timeout: 5s
      start_period: 60s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  frontend:
    image: ghcr.io/epitech-msc-1/time-manager-frontend:${TAG:-latest}
    environment:
      VITE_API_URL: https://api.ytlabs.space/graphql
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -sf http://localhost:9000/api/system/status | grep -q ''"status":"UP"'''
      interval: 10s
      timeout: 10s
      start_period: 60s
      retries: 10
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mkdocs:
    image: ghcr.io/epitech-msc-1/time-manager-mkdocs:${TAG:-latest}
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  default:
    name: time-manager-net
    driver: overlay
    attachable: true

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  db_data:
  traefik-certs:
