# Generated by Django 5.2.7 on 2025-10-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeBankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='timeclock',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
