# Generated by Django 5.2.7 on 2025-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PrimeBankApp", "0003_remove_team_members_nr_alter_customuser_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
