# Generated by Django 5.2.7 on 2025-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeBankApp', '0004_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='clock_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out',
            field=models.TimeField(null=True),
        ),
    ]
