# Generated by Django 5.2.7 on 2025-10-23 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeBankApp', '0005_alter_timeclock_clock_in_alter_timeclock_clock_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModifyTimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_clock_in', models.TimeField(blank=True, null=True)),
                ('old_clock_out', models.TimeField(blank=True, null=True)),
                ('new_clock_in', models.TimeField(blank=True, null=True)),
                ('new_clock_out', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_modify_time_clock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
