# Generated by Django 5.2.7 on 2025-10-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeBankApp', '0006_requestmodifytimeclock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodifytimeclock',
            name='old_clock_in',
        ),
        migrations.RemoveField(
            model_name='requestmodifytimeclock',
            name='old_clock_out',
        ),
    ]
