# Generated by Django 5.2.7 on 2025-10-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeBankApp', '0007_remove_requestmodifytimeclock_old_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodifytimeclock',
            name='old_clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmodifytimeclock',
            name='old_clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
