name: Mirror Repository

on:
  pull_request_target:
    types: [closed]
    branches:
      - main
      - dev
jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          token: ${{ secrets.MIRROR_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add mirror remote
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
          MIRROR_REPO_URL: ${{ vars.MIRROR_REPO_URL }}
        run: |
          if [ -z "${MIRROR_REPO_URL}" ]; then
            echo "MIRROR_REPO_URL is not set"
            exit 1
          fi
          SANITIZED_URL="${MIRROR_REPO_URL#https://}"
          SANITIZED_URL="${SANITIZED_URL#http://}"
          SANITIZED_URL="${SANITIZED_URL#/}"
          git remote add mirror "https://${MIRROR_TOKEN}@${SANITIZED_URL}"

      - name: Debug - Check current state
        run: |
          echo "Current HEAD: $(git rev-parse HEAD)"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
          echo "Available branches:"
          git branch -a
          echo "Current commit info:"
          git log --oneline -1

      - name: Push to mirror
        run: |
          BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          echo "Pushing HEAD to branch: $BRANCH_NAME"
          git push mirror HEAD:$BRANCH_NAME --force
          git push mirror --tags --force
